# ENV
CC = g++
# CC = clang --analyze # and comment out the linker last line for sanity
EIGENROOT ?= /home/bingqingqu/user-libs/eigen-3.2.4

BIN_DIR := ./bin
SRC_DIR := ./src
LIB_DIR := ./lib
INC_DIR := ./include
OBJ_DIR := ./obj

# FLAGS
CFLAGS := -g -Wall  -std=c++0x -O3 -I$(EIGENROOT) -I$(INC_DIR)/
LDFLAGS :=

# custom functions
# rule to create a directory
.PRECIOUS: %/.dirstamp
%/.dirstamp :
	@printf "%10s %s\n" MK "$(dir $@)"
	@mkdir -p $(dir $@)
	@echo "Directory generated by make." > $@

# $(call gendir, TARGET, DIR1 DIR2 ...) creates a target TARGET-dir that
# triggers the creation of the directories DIR1, DIR2
define gendir
$(1)=$(foreach x,$(2),$(x)/.dirstamp)
endef

SOURCES:= $(wildcard $(SRC_DIR)/cpp/*.cpp)
OBJECTS:= $(patsubst $(SRC_DIR)/cpp/%,$(OBJ_DIR)/%,$(SOURCES:.cpp=.o))
BIN_SRC:= $(wildcard $(SRC_DIR)/tests/*.cpp)
BIN_TGT:= $(addprefix $(BIN_DIR)/, $(patsubst %.cpp,%,$(notdir $(BIN_SRC))))

# generate the all-dir target
$(eval $(call gendir, dirs, $(BIN_DIR) $(OBJ_DIR) ))

.PRECIOUS: $(OBJECTS)
all: $(BIN_TGT)


$(BIN_DIR)/%: $(SRC_DIR)/tests/%.cpp $(OBJECTS) $(dirs)
	@echo "	Linking..."
	@echo "	$(CC) $(CFLAGS) $< $(OBJECTS) $(LDFLAGS) -o $@";  \
	$(CC) $(CFLAGS) $< $(OBJECTS) $(LDFLAGS) -o $@

$(OBJ_DIR)/%.o: $(SRC_DIR)/cpp/%.cpp $(dirs)
	@mkdir -p $(OBJ_DIR)
	@echo "	$(CC) $(CFLAGS) -c -o $@ $<"; $(CC) $(CFLAGS) -c -o $@ $<


clean:
	@echo "	Cleaning..."
	@echo "	$(RM) -r $(OBJ_DIR) $(BIN_DIR)"; $(RM) -r $(OBJ_DIR) $(BIN_DIR)/*

.PHONY: clean all
